### ISSUE TITLE
Is DVC model trained in a progressive manner ?

### ISSUE THREAD

**Issue by GraceZhuuu** [ZhihaoHu/PyTorchVideoCompression#18]
I saw `Trainstage` function in FVC model, but i can't find something like that to show training in a progressive manner in DVC.

**Comment by WenBingo** [comment]
> I saw `Trainstage` function in FVC model, but i can't find something like that to show training in a progressive manner in DVC.

i run the project of FVC, but i have some question,  please help me .
I down the data of ' vimeo_septuplet', in that has one 'sep_testlist.txt' .  I change the code of 'dataset.py' where 'test.txt' towards 'sep_testlist.txt', but  i get Eorr.  In the code of 'curnumber= int(y[-5:-4]) '  i get the " y = '\' " .

    y = os.path.join(rootdir, line.rstrip())
        curnumber = int(y[-5:-4])
        refnumber = curnumber - 2
        if refnumber < 1:
            continue
            
  I do not understand this code .
Please help me , if possible we can talk in Wechat , my Wechat ID is 18921762605

**Comment by WenBingo** [comment]
> I saw `Trainstage` function in FVC model, but i can't find something like that to show training in a progressive manner in DVC.

please help me  ，I can 't solve the problem， please

**Comment by WenBingo** [comment]
> I saw `Trainstage` function in FVC model, but i can't find something like that to show training in a progressive manner in DVC.
Want to ask whether we need to design a test.txt file.？？
