### ISSUE TITLE
Where are the pretrained SpyNet model weights?

### ISSUE THREAD

**Issue by Somdyuti2** [ZhihaoHu/PyTorchVideoCompression#4]
Hi, could you please provide the pretrained model weights for the SpyNet ME module? I think this is not provided and I am getting a runtime error `[Errno 2] No such file or directory: '../flow_pretrain_np/modelL1_F-1-weight.npy'`. Thanks.

**Comment by JAS0NN** [comment]
The pretrained model weights are located at `DVC/examples/flow_pretrain_np`

**Comment by Somdyuti2** [comment]
Thanks.
